version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql_container_graphql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_api_graphql
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"

volumes:
  db_data: